services:

  mongodb:
    container_name: gdh-inter-db-mongo
    image: mongo:6.0.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27018"

  redis:
    container_name: gdh-inter-bus-redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6380:6380"

  udata:
    container_name: gdh-inter-app-udata
    build: .
    links:
      - mongodb:mongodb
      - redis:redis
    volumes:
      - udata-fs:/udata/fs
      - ../udata-front-sbe:/src/udata-front
    ports:
      - "7010:7010"
    command: serve --host 0.0.0.0 --port 7010 --debugger --reload
    environment:
      - FLASK_DEBUG=true

volumes:
  udata-fs:
  mongo-data:
  redis-data:
  # udata-front:

networks:
  default:
    name: gdh-inter-udata
    external: true
    ipam:
      driver: bridge
      config:
        - subnet: 172.16.0.0/29

